# Change these first
owner: grouparoo # Your GitHub username
repo: upptime # Your GitHub repository name

sites:
  # Grouparoo Properties
  - name: www.grouparoo.com
    url: https://www.grouparoo.com
    icon: https://www.grouparoo.com/favicon/favicon-196x196.png
  - name: telemetry.grouparoo.com
    url: https://telemetry.grouparoo.com
    icon: https://www.grouparoo.com/favicon/favicon-196x196.png

status-website:
  cname: status.grouparoo.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/grouparoo/grouparoo/master/ui/public/%40grouparoo/logo.png
  name: Upptime
  introTitle: "**Upptime**: Monitoring Grouparoo"
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/grouparoo/upptime). No server required — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Back to Grouparoo
      href: https://www.grouparoo.com
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
